# Generated by Django 5.2 on 2025-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentRegNumber', models.CharField(max_length=50, unique=True)),
                ('StudentName', models.CharField(max_length=100, unique=True)),
                ('NameOfTheProgramme', models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD')], max_length=10)),
                ('StudentAddress', models.TextField()),
                ('ContactMobileNumber', models.CharField(max_length=10)),
                ('StatusOftheSemesterFee', models.CharField(choices=[('PAID', 'Paid'), ('NOT', 'Not Paid')], default='NOT', max_length=10)),
            ],
        ),
    ]
