# Generated by Django 5.2.1 on 2025-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalStudent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentRegNumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
